### ISSUE TITLE
missing commercial lengths in pacfin

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/CA_quillback_rockfish_2025#20]
There are 146 samples in pacfin that do not have lengths associated with them. These occur nearly entirely in 2018 and 2019 for one port. This is surprising and makes me wonder whether the data truly dont exist, or if there was an issue with their lengths and thus they are assigned NA somewhere in our process.

**Comment by melissamonk-NOAA** [comment]
@brianlangseth-NOAA, because this is fairly isolated, my initial exploratory look makes me think this may be due to refusal.

**Comment by brianlangseth-NOAA** [comment]
These were species composition samples only so no lengths were taken
